name: Code Quality (Rector & Pint)

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4' # Pas aan naar jouw versie
          extensions: mbstring, xml, ctype, iconv, mysql
          coverage: none

      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist

      # 1. Run Rector in Dry-run mode (geeft error als er refactors nodig zijn)
      - name: Run Rector (Dry Run)
        run: ./vendor/bin/rector process --dry-run

      # 2. Run Laravel Pint (geeft error als PSR-stijl niet klopt)
      - name: Run Pint
        run: ./vendor/bin/pint --test
